version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

  api:
    build:
      context: ./flight-book-api
      dockerfile: Dockerfile
    container_name: flight-book-api
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - redis
    env_file:
      - ./flight-book-api/.env
    volumes:
      - ./flight-book-api:/usr/src/app
    command: npm run start:dev
    restart: always

  app:
    build:
      context: ./flight-book-app
      dockerfile: Dockerfile
    container_name: flight-book-app
    ports:
      - '3000:3000'
    depends_on:
      - api
    env_file:
      - ./flight-book-app/.env
    volumes:
      - ./flight-book-app:/usr/src/app
    command: npm start
    restart: always

volumes:
  mongo-data:
  redis-data:
