version: '3.8'

services:
  # Backend service
  app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/flightsdb
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

# Volumes to persist MongoDB data
volumes:
  mongo-data: